import type { Metadata } from "next";
import { ThemeProvider } from '@/components/theme-provider';
import { fonts } from './fonts';
import "@/styles/globals-minify.css";

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <head>
        <title>My Next App</title>
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
